import { Email, EmailStatus, Sentiment } from './types';

export const getDemoEmails = (): Email[] => {
  const now = new Date();
  
  const createDate = (daysAgo: number, hoursAgo: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() - daysAgo);
    d.setHours(d.getHours() - hoursAgo);
    return d.toISOString();
  };

  return [
    {
      id: '#DEMO-AX19Q2',
      from: 'noreply@demo-intranet.local',
      to: 'qualitaet@demo-firma.eu',
      subject: 'Filialreklamation: Landbrot Rustikal zu dunkel',
      date: createDate(2, 4),
      body: 'Meldung von Mara Lehmann (F12):\n\nDas gelieferte Landbrot Rustikal war heute Morgen bei mehreren Laiben deutlich zu dunkel gebacken. Die Kruste ist fast schwarz und schmeckt bitter.',
      summary: 'Mehrere Laibe Landbrot Rustikal in Filiale 12 sind zu dunkel gebacken und unverkaufbar.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Produktqualität',
      product: 'Landbrot Rustikal',
      branch: 'Filiale 12 – Bahnhof',
      reason: 'Zu dunkel gebacken',
      employeeId: '1024',
      employeeName: 'Mara Lehmann (F12)',
      status: EmailStatus.OPEN,
      isDemo: true,
      images: ['https://picsum.photos/seed/burnt-bread/800/600']
    },
    {
      id: '#DEMO-KB77P1',
      from: 'support@beispiel-baeckerei.de',
      to: 'zentrale@demo-firma.eu',
      subject: 'Qualitätsmangel: Vollkornbrötchen teigig',
      date: createDate(5, 2),
      body: 'Bericht von Jonas Richter (F08):\n\nDie Vollkornbrötchen der heutigen Lieferung sind im Kern noch teigig und nicht vollständig durchgebacken. Wir mussten die gesamte Charge aus dem Verkauf nehmen.',
      summary: 'Vollkornbrötchen in Filiale 08 sind nicht vollständig durchgebacken.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Produktqualität',
      product: 'Vollkornbrötchen',
      branch: 'Filiale 08 – Zentrum',
      reason: 'Nicht vollständig durchgebacken',
      employeeId: '1155',
      employeeName: 'Jonas Richter (F08)',
      status: EmailStatus.IN_PROGRESS,
      isDemo: true
    },
    {
      id: '#DEMO-SW33M4',
      from: 'qualitaet@demo-firma.eu',
      to: 'zentrale@demo-firma.eu',
      subject: 'Hygienehinweis Filiale Nord',
      date: createDate(10, 8),
      body: 'Hinweis von Sina Weber (F21):\n\nIm Thekenbereich der Filiale 21 wurde eine Verschmutzung festgestellt, die umgehend beseitigt werden muss. Die Reinigungspläne wurden nicht korrekt dokumentiert.',
      summary: 'Hygienemängel und fehlende Dokumentation in Filiale 21 festgestellt.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Hygiene',
      product: 'N/A',
      branch: 'Filiale 21 – Nord',
      reason: 'Hygiene',
      employeeId: '1288',
      employeeName: 'Sina Weber (F21)',
      status: EmailStatus.OPEN,
      isDemo: true
    },
    {
      id: '#DEMO-TR88L2',
      from: 'support@beispiel-baeckerei.de',
      to: 'zentrale@demo-firma.eu',
      subject: 'Kommissionierfehler Filiale West',
      date: createDate(15, 1),
      body: 'Meldung der Filiale 03:\n\nAnstelle der bestellten 50 Körnerbaguettes wurden uns heute 50 normale Baguettes geliefert. Die Kunden fragen bereits nach der Vollkorn-Variante.',
      summary: 'Falsche Ware geliefert: Normale Baguettes statt Körnerbaguettes in Filiale 03.',
      sentiment: Sentiment.NEUTRAL,
      category: 'Kommissionierfehler',
      product: 'Körnerbaguette',
      branch: 'Filiale 03 – West',
      reason: 'Kommissionierfehler',
      employeeId: '1402',
      employeeName: 'Team West',
      status: EmailStatus.CLOSED,
      isDemo: true
    },
    {
      id: '#DEMO-QM55S9',
      from: 'noreply@demo-intranet.local',
      to: 'qualitaet@demo-firma.eu',
      subject: 'Transportschaden: Schoko-Muffins beschädigt',
      date: createDate(20, 5),
      body: 'Bericht von Mara Lehmann (F12):\n\nDie Schoko-Muffins sind heute in einem beschädigten Zustand angekommen. Die Verpackung war eingedrückt, wodurch die Glasur an der Folie klebt.',
      summary: 'Transportschaden bei Schoko-Muffins in Filiale 12. Ware optisch beeinträchtigt.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Falscher Transport',
      product: 'Schoko-Muffin',
      branch: 'Filiale 12 – Bahnhof',
      reason: 'Falscher Transport',
      employeeId: '1024',
      employeeName: 'Mara Lehmann (F12)',
      status: EmailStatus.OPEN,
      isDemo: true,
      images: ['https://picsum.photos/seed/damaged-muffin/800/600']
    },
    {
      id: '#DEMO-ZZ11X0',
      from: 'qualitaet@demo-firma.eu',
      to: 'zentrale@demo-firma.eu',
      subject: 'Lob zur Produktqualität',
      date: createDate(25, 12),
      body: 'Feedback von Jonas Richter (F08):\n\nDas Landbrot Rustikal ist diese Woche von hervorragender Qualität. Die Kunden loben besonders die krosse Kruste und den Geschmack.',
      summary: 'Sehr positives Kundenfeedback zur Qualität des Landbrots in Filiale 08.',
      sentiment: Sentiment.POSITIVE,
      category: 'Sonstiges',
      product: 'Landbrot Rustikal',
      branch: 'Filiale 08 – Zentrum',
      reason: 'Qualität entspricht der Erwartung',
      employeeId: '1155',
      employeeName: 'Jonas Richter (F08)',
      status: EmailStatus.CLOSED,
      isDemo: true
    },
    {
      id: '#DEMO-PP22Y3',
      from: 'support@beispiel-baeckerei.de',
      to: 'zentrale@demo-firma.eu',
      subject: 'Reklamation: Vollkornbrötchen zu dunkel',
      date: createDate(30, 3),
      body: 'Meldung von Mara Lehmann (F12):\n\nErneut sind die Vollkornbrötchen heute deutlich zu dunkel gebacken. Wir mussten 20 Stück aussortieren.',
      summary: 'Wiederholter Qualitätsmangel: Zu dunkel gebackene Vollkornbrötchen in Filiale 12.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Produktqualität',
      product: 'Vollkornbrötchen',
      branch: 'Filiale 12 – Bahnhof',
      reason: 'Zu dunkel gebacken',
      employeeId: '1024',
      employeeName: 'Mara Lehmann (F12)',
      status: EmailStatus.IN_PROGRESS,
      isDemo: true
    },
    {
      id: '#DEMO-RR44Z5',
      from: 'noreply@demo-intranet.local',
      to: 'qualitaet@demo-firma.eu',
      subject: 'Backfehler: Buttercroissants teigig',
      date: createDate(35, 6),
      body: 'Bericht von Jonas Richter (F08):\n\nDie Buttercroissants sind heute innen noch sehr teigig. Es scheint, als wäre die Backtemperatur zu niedrig gewesen.',
      summary: 'Buttercroissants in Filiale 08 sind nicht durchgebacken.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Produktqualität',
      product: 'Buttercroissant',
      branch: 'Filiale 08 – Zentrum',
      reason: 'Nicht vollständig durchgebacken',
      employeeId: '1155',
      employeeName: 'Jonas Richter (F08)',
      status: EmailStatus.OPEN,
      isDemo: true
    },
    {
      id: '#DEMO-TT66A7',
      from: 'qualitaet@demo-firma.eu',
      to: 'zentrale@demo-firma.eu',
      subject: 'Sauberkeit im Außenbereich',
      date: createDate(40, 2),
      body: 'Hinweis von Sina Weber (F21):\n\nDer Außenbereich der Filiale 21 muss gründlicher gereinigt werden. Es liegen vermehrt Krümel und Servietten auf dem Boden.',
      summary: 'Mangelnde Sauberkeit im Außenbereich der Filiale 21 gemeldet.',
      sentiment: Sentiment.NEGATIVE,
      category: 'Hygiene',
      product: 'N/A',
      branch: 'Filiale 21 – Nord',
      reason: 'Hygiene',
      employeeId: '1288',
      employeeName: 'Sina Weber (F21)',
      status: EmailStatus.CLOSED,
      isDemo: true
    },
    {
      id: '#DEMO-UU88B9',
      from: 'support@beispiel-baeckerei.de',
      to: 'zentrale@demo-firma.eu',
      subject: 'Fehlmenge bei Lieferung',
      date: createDate(45, 10),
      body: 'Meldung der Filiale 03:\n\nBei der heutigen Lieferung der Schoko-Muffins fehlten 10 Stück laut Lieferschein. Bitte um Gutschrift.',
      summary: 'Fehlmenge bei Schoko-Muffins in Filiale 03 festgestellt.',
      sentiment: Sentiment.NEUTRAL,
      category: 'Kommissionierfehler',
      product: 'Schoko-Muffin',
      branch: 'Filiale 03 – West',
      reason: 'Kommissionierfehler',
      employeeId: '1402',
      employeeName: 'Team West',
      status: EmailStatus.OPEN,
      isDemo: true
    }
  ];
};
